# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contactno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
