# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxlogin', '0002_auto_20180313_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
