# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxlogin', '0003_auto_20180313_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contactno',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
