# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxlogin', '0004_auto_20180314_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='contactno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
