# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxlogin', '0005_auto_20180314_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Logins',
        ),
    ]
