# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxlogin', '0006_auto_20180314_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logins',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
